[package]
name = "csv_payment"
version = "0.1.0"
authors = ["Alberto Fernandez"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = { version = "1", features = ["derive"] }
serde_derive = "1.0"
csv = "1.1"
